version: 2
updates:
- package-ecosystem: mix
  directory: "/"
  schedule:
    interval: daily
    time: "20:00"
  ignore:
  - dependency-name: ex_doc
    versions:
    - 0.24.0
    - 0.24.1
  - dependency-name: earmark
    versions:
    - 1.4.14
  - dependency-name: excoveralls
    versions:
    - 0.13.4
  - dependency-name: exvcr
    versions:
    - 0.12.2
