on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-elixir@v1
        with:
          otp-version: '23.0'
          elixir-version: '1.11.2'
      - run: mix deps.get
      - run: mix test
